M2-LZ-33
Latwe-Zdanko/IO2020 pull request #16
Opened 2020-05-24 20:04 UTC by agsta

Ankieta do makiety

2020-05-25 09:02 UTC, jakubrog requested changes
fix your build and everything will be great

2020-05-25 13:22 UTC, mimagiera commented on src/main/java/lz/modelTesting/configuration/MongoDBConfig.java
> +import java.util.*;
Not a problem but be aware of it:
https://stackoverflow.com/questions/147454/why-using-a-wild-card-with-a-java-import-statement-bad

2020-05-25 13:22 UTC, mimagiera commented on src/main/java/lz/modelTesting/controllers/SurveysController.java
> +        survey.setMockupId(new JSONObject(postPayload).getString(MOCKUP_ID));
* Maybe better create another constructor of survey with mockupId?
* you already have variable `mockupId`

2020-05-25 13:23 UTC, mimagiera commented on src/main/java/lz/modelTesting/controllers/SurveysController.java
> +        survey.setMockupId(new JSONObject(postPayload).getString(MOCKUP_ID));
+ there already exists method `getSurveyFromJson`

2020-05-26 20:20 UTC, Eternalynx requested changes
Bardzo dobry kod. Nie widzę większych problemów, jedynie kosmetykę w paru miejscach.

2020-05-26 20:20 UTC, Eternalynx commented on front/src/components/AddMockupSurvey.js
> +            isFull: false,
Probably would have changed name isFull to isFullscreen. isFull might mean different things. isFullscreen is more precise

2020-05-26 20:20 UTC, Eternalynx commented on front/src/components/MockupSurvey.js
> +            isFull: false,
Again isFull probably should be changed to isFullscreen

2020-05-26 22:09 UTC, jakubrog approved these changes

2020-05-27 02:00 UTC, Eternalynx approved these changes

2020-05-27 13:31 UTC, merged